# Prometheus configuration for GMAC.IO Control Panel monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'gmac-k3s'
    environment: 'production'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Control Panel application metrics
  - job_name: 'control-panel'
    scrape_interval: 30s
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['control-panel-service.control-panel.svc.cluster.local:80']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: control-panel-service.control-panel.svc.cluster.local:80

  # Kubernetes API server
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
    - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: false
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: default;kubernetes;https

  # Kubernetes nodes
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
    - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: false
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: kubernetes.default.svc:443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics

  # Kubernetes pods
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name

  # External integrations
  - job_name: 'gitea'
    scrape_interval: 60s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['git.gmac.io:3000']
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'drone'
    scrape_interval: 60s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ci.gmac.io:443']
    scheme: https
    
  - job_name: 'harbor'
    scrape_interval: 60s
    metrics_path: '/api/v2.0/metrics'
    static_configs:
      - targets: ['registry.gmac.io:443']
    scheme: https

  # Node exporters (if deployed)
  - job_name: 'node-exporter'
    static_configs:
      - targets: 
        - 'node-exporter.monitoring.svc.cluster.local:9100'

  # PostgreSQL exporter (if deployed)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets:
        - 'postgres-exporter.control-panel.svc.cluster.local:9187'

  # Redis exporter (if deployed)
  - job_name: 'redis-exporter'
    static_configs:
      - targets:
        - 'redis-exporter.control-panel.svc.cluster.local:9121'