apiVersion: v1
kind: Secret
metadata:
  name: control-panel-secrets
  namespace: control-panel
type: Opaque
stringData:
  GITHUB_ID: "your_github_client_id"
  GITHUB_SECRET: "your_github_client_secret"
  NEXTAUTH_URL: "https://gmac.io"
  NEXTAUTH_SECRET: "k9rkeNZkDH5J+OJgpHAGobAXQQJR+AERbQQFQv94u+4="
  TURSO_DATABASE_URL: "your_turso_database_url"
  TURSO_AUTH_TOKEN: "your_turso_auth_token"
  OAUTH_TOKEN: "your-oauth-token-here"
  NEXT_PUBLIC_GITEA_TOKEN: "your-gitea-token-here"
  NEXT_PUBLIC_K8S_TOKEN: "your-k8s-service-account-token"
  STRIPE_SECRET_KEY: "your_stripe_secret_key"