apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-panel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://git.gmac.io/gmackie/control-panel
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: control-panel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  
---
apiVersion: v1
kind: Secret
metadata:
  name: control-panel-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://git.gmac.io/gmackie/control-panel
  # If the repository requires authentication, add:
  # username: gitea-username
  # password: gitea-token-or-password