fullnameOverride: promtail

# Keep this promtail instance on the worker node only.
nodeSelector:
  kubernetes.io/hostname: k3s-worker-1

initContainer:
  - name: init-inotify
    image: docker.io/busybox:1.36
    imagePullPolicy: IfNotPresent
    command:
      - sh
      - -c
      - sysctl -w fs.inotify.max_user_instances=1024 fs.inotify.max_user_watches=524288
    securityContext:
      privileged: true

config:
  clients:
    - url: http://loki-gateway/loki/api/v1/push

  # Avoid hitting file descriptor limits on nodes with many historical pods.
  snippets:
    extraRelabelConfigs:
      - action: keep
        source_labels:
          - __meta_kubernetes_pod_phase
        regex: Running
      - action: keep
        source_labels:
          - __meta_kubernetes_pod_node_name
        regex: k3s-worker-1
